Add putEncrypted with public key
savoirfairelinux/opendht pull request #558
Opened 2021-05-27 19:52 UTC by aberaud

2021-05-28 13:02 UTC, oldiob requested changes
I don't think you need to lock `store_mtx` to access the running state.

You also don't need to lock it for accessing ongoing_ops.

I might be missing something here.

2021-05-28 14:43 UTC, aberaud commented on src/dhtrunner.cpp
> +        }
Indeed, done.

2021-05-28 14:43 UTC, aberaud commented on src/dhtrunner.cpp
> +        lck.unlock();
* We now want to guarantee that no operation will be scheduled on pending_ops after `shutdown` or `join`. There was a possibility that shutdown would occur while one of these ops was waiting on the mutex, but after checking `running`.
* storage_mtx was locked anyway, so locking it a bit earlier has a trivial performance impact.
* We want to call the callback unlocked to allow the callback to act on the dht without deadlock.

2021-06-07 17:44 UTC, AmarOk1412 approved these changes

2021-06-07 18:45 UTC, merged