Search duplicate put
savoirfairelinux/opendht pull request #734
Opened 2024-11-18 16:07 UTC by aberaud

2024-11-19 22:44 UTC, fsimonfc requested changes

2024-11-19 22:44 UTC, fsimonfc commented on tests/dhtrunnertester.h
> +    CPPUNIT_TEST(testPutDuplicate);
Missing `CPPUNIT_TEST(testPutOverride);`

2024-11-19 22:44 UTC, fsimonfc commented on tests/dhtrunnertester.cpp
> +    auto val_data = val->data;
`val2->data`

2024-11-20 15:57 UTC, aberaud commented on tests/dhtrunnertester.cpp
> +    auto val_data = val->data;
Done

2024-11-20 15:57 UTC, aberaud commented on tests/dhtrunnertester.h
> +    CPPUNIT_TEST(testPutDuplicate);
Done

2024-11-20 16:16 UTC, fsimonfc approved these changes

2024-11-20 16:39 UTC, merged